# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://iostiny.me
date_format: "ordinal"
title: Rick's Blog
subtitle: "Some Thing Are Better Done than Described"
description: "施为的个人博客"
keywords: Orange, iostiny, 橘子猿
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Rick Shi
organization: Happigo Ltd.
organization_url: http://www.happigo.com
location: Changsha, China
email: iostiny@yahoo.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

#  -
#    href: /links/
#    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: iostiny/iostiny.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: iostiny
# izhihu_username: mzlogin
twitter_username: iostiny

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: iostiny
disqus_username: iostiny
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
# google:
#    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [C, C++, Objective-C, Swift, Python, Design Patterns]
skill_mobile_app_keywords: [iOS, Reverse Engineering]
# skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]
